name: pickkaru
description: A minimal scaffold for Pickkaru commute app
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  google_sign_in: ^6.1.0
  flutter_riverpod: ^2.5.0
  mapbox_maps_flutter: ^2.0.0
  geolocator: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true