// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBICH1zOfPY50tjdCWXe1oHDGqtymHtufQ',
    appId: '1:671801788510:web:71ff9e32bff0718250cccf',
    messagingSenderId: '671801788510',
    projectId: 'phrasal-alpha-407309',
    authDomain: 'phrasal-alpha-407309.firebaseapp.com',
    storageBucket: 'phrasal-alpha-407309.firebasestorage.app',
    measurementId: 'G-NBLY4W0N4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtyzDvGjCJgv9YHi3jEjSQQhwzDnOYMB4',
    appId: '1:671801788510:android:0037703e3b5222c650cccf',
    messagingSenderId: '671801788510',
    projectId: 'phrasal-alpha-407309',
    storageBucket: 'phrasal-alpha-407309.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6GbFNSbJngED3CUHGS2yHSqUm4zSaD_k',
    appId: '1:671801788510:ios:c4d0f8d1287cb63450cccf',
    messagingSenderId: '671801788510',
    projectId: 'phrasal-alpha-407309',
    storageBucket: 'phrasal-alpha-407309.firebasestorage.app',
    androidClientId: '671801788510-3jbpbcrsghhtqgsjd73vt06g047cr9qb.apps.googleusercontent.com',
    iosClientId: '671801788510-0j6uqcfjco1616k9talt7dlqoe0bhj6k.apps.googleusercontent.com',
    iosBundleId: 'com.app.pickkaru',
  );

}
